import type { CityInfo } from '@/types';

export const LAUNCH_CITIES: CityInfo[] = [
  {
    id: 'tokyo',
    name: 'Tokyo',
    tagline: 'Chaos with impeccable taste',
    country: 'Japan',
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: 'Asia/Tokyo',
    gradient: 'from-rose-500/20 via-pink-500/10 to-fuchsia-500/20',
  },
  {
    id: 'berlin',
    name: 'Berlin',
    tagline: 'The city that never sleeps (because the clubs never close)',
    country: 'Germany',
    latitude: 52.52,
    longitude: 13.405,
    timezone: 'Europe/Berlin',
    gradient: 'from-zinc-500/20 via-neutral-500/10 to-stone-500/20',
  },
  {
    id: 'mexico-city',
    name: 'Mexico City',
    tagline: 'Where every street is a flavor',
    country: 'Mexico',
    latitude: 19.4326,
    longitude: -99.1332,
    timezone: 'America/Mexico_City',
    gradient: 'from-orange-500/20 via-amber-500/10 to-yellow-500/20',
  },
  {
    id: 'lisbon',
    name: 'Lisbon',
    tagline: 'Faded grandeur meets late-night magic',
    country: 'Portugal',
    latitude: 38.7223,
    longitude: -9.1393,
    timezone: 'Europe/Lisbon',
    gradient: 'from-sky-500/20 via-cyan-500/10 to-teal-500/20',
  },
  {
    id: 'nyc',
    name: 'New York City',
    tagline: 'Eight million stories, none of them boring',
    country: 'United States',
    latitude: 40.7128,
    longitude: -74.006,
    timezone: 'America/New_York',
    gradient: 'from-amber-500/20 via-yellow-500/10 to-orange-500/20',
  },
  {
    id: 'paris',
    name: 'Paris',
    tagline: 'Romance is overrated — the food is the real love story',
    country: 'France',
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: 'Europe/Paris',
    gradient: 'from-violet-500/20 via-purple-500/10 to-indigo-500/20',
  },
  {
    id: 'london',
    name: 'London',
    tagline: 'Dry wit, wet weather, world-class everything',
    country: 'United Kingdom',
    latitude: 51.5074,
    longitude: -0.1278,
    timezone: 'Europe/London',
    gradient: 'from-blue-500/20 via-slate-500/10 to-indigo-500/20',
  },
  {
    id: 'bangkok',
    name: 'Bangkok',
    tagline: 'Sensory overload in the best way',
    country: 'Thailand',
    latitude: 13.7563,
    longitude: 100.5018,
    timezone: 'Asia/Bangkok',
    gradient: 'from-emerald-500/20 via-green-500/10 to-lime-500/20',
  },
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    tagline: 'Dinner at midnight, dancing at 3am',
    country: 'Argentina',
    latitude: -34.6037,
    longitude: -58.3816,
    timezone: 'America/Argentina/Buenos_Aires',
    gradient: 'from-cyan-500/20 via-blue-500/10 to-indigo-500/20',
  },
  {
    id: 'istanbul',
    name: 'Istanbul',
    tagline: 'Two continents, one incredible night',
    country: 'Turkey',
    latitude: 41.0082,
    longitude: 28.9784,
    timezone: 'Europe/Istanbul',
    gradient: 'from-red-500/20 via-rose-500/10 to-amber-500/20',
  },
];

export const CITY_MAP = Object.fromEntries(LAUNCH_CITIES.map((c) => [c.id, c])) as Record<
  string,
  CityInfo
>;
